datepicker
diverta/front_nuxt_corporate pull request #19
Opened 2024-04-22 12:45 UTC by VortexExpansion

@yabe-diverta san 
https://diverta.gyazo.com/744da4236120def49005c9468d7073f3

2024-05-09 05:12 UTC, yabe-diverta requested changes
Could you add i18n plugin for Japanese?

2024-05-09 05:18 UTC, VortexExpansion commented
But front_nuxt_corporate is already fully in japanese.

2024-05-09 05:23 UTC, yabe-diverta commented
@VortexExpansion 
I thought the datepicker should be Japanese, not the other elements.
Am I missing something?

2024-05-09 05:34 UTC, VortexExpansion commented
Oh maybe I see what you mean. 
This site (unlike front_nuxt_auth) has no language button for switching. 

But maybe you mean keep the datepicker only in japanese and not in default english implementation right ?

2024-05-09 05:36 UTC, yabe-diverta commented
@VortexExpansion 
exactly~~~

2024-05-09 05:41 UTC, VortexExpansion commented
@yabe-diverta san 
Added https://diverta.gyazo.com/2cd2f687d93333665a9d42114c31d7a0
Please confirm.

2024-05-09 05:53 UTC, yabe-diverta requested changes

2024-05-09 05:53 UTC, yabe-diverta commented on pages/contact/index.vue
When it comes to typical custom about Japanese calendar,
- weeks start with Sunday
- ordering for date string differs to West (yyyy/MM/dd is JP, MM/dd/yyyy is EN)
https://diverta.gyazo.com/df8e12dfcca875f3b1739cc5696666c9

2024-05-09 09:13 UTC, VortexExpansion commented
@yabe-diverta  san 

Formatted according to typical Japanese calendar. https://diverta.gyazo.com/11687d4253544c10dff68c60d97a26bd
Please check now

2024-05-16 05:56 UTC, yabe-diverta approved these changes
Thank you to fix, no issues 🙇

2024-05-24 07:05 UTC, VortexExpansion commented
@HisashiHasebe san 
Please confirm and merge

2024-05-24 07:14 UTC, merged